name: Make release

on:
  workflow_dispatch:
    inputs:
      gamelift:
        description: 'GameLift ZIPed sources'
        default: 'GameLift-Cpp-ServerSDK-5.0.4'
        required: true
        type: string
      tag:
        description: 'A version tag'
        default: '0.0'
        required: true
        type: string

jobs:
  gamelift_build_linux:
    name: Build and upload Linux binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download and unzip gamelift
      run: |
       sudo apt-get update
       sudo apt-get install -y unzip
       wget https://gamelift-server-sdk-release.s3.us-west-2.amazonaws.com/cpp/${{ inputs.gamelift }}.zip -O gamelift.zip
       unzip -q gamelift.zip
       ls
       cd ${{ inputs.gamelift }}

    - name: Install tools
      run: |
       sudo apt-get update
       sudo apt-get install -y cmake
       sudo apt-get install -y gcc
       sudo apt-get install -y g++

    - name: Configure and build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_FOR_UNREAL=1 -DRUN_CLANG_FORMAT=0
        cmake --build build -j
       
